### ISSUE TITLE
Custom validator doesn't work

### ISSUE THREAD

**Issue by vadim-shilov** [icebob/fastest-validator#105]
I've tried to run an example from documentation :(

version: 1.0.0

```
const Validator = require('fastest-validator');

let v = new Validator({
  messages: {
    // Register our new error message text
    weightMin: "The weight must be greater than {expected}! Actual: {actual}"
  }
});

const schema = {
  name: { type: "string", min: 3, max: 255 },
  weight: {
    type: "custom",
    minWeight: 10,
    check(value, schema) {
      return (value < schema.minWeight)
        ? this.makeError("weightMin", schema.minWeight, value)
        : true;
    }
  }
};

console.log(v.validate({ name: "John", weight: 50 }, schema));
// Returns: true

console.log(v.validate({ name: "John", weight: 8 }, schema));
```
Result:
```
/home/vadim/.WebStorm2019.3/config/scratches/scratch.es6:296
        ? this.makeError("weightMin", schema.minWeight, value)
               ^

TypeError: this.makeError is not a function
    at Array.check (/home/vadim/.WebStorm2019.3/config/scratches/scratch.es6:296:16)
    at Array.eval (eval at compileRule (/home/vadim/Projects/Elysium/api/node_modules/fastest-validator/lib/validator.js:224:16), <anonymous>:5:34)
    at Array.eval (eval at compileRule (/home/vadim/Projects/Elysium/api/node_modules/fastest-validator/lib/validator.js:224:16), <anonymous>:31:33)
    at Validator.eval (eval at compile (/home/vadim/Projects/Elysium/api/node_modules/fastest-validator/lib/validator.js:170:19), <anonymous>:10:14)
    at /home/vadim/Projects/Elysium/api/node_modules/fastest-validator/lib/validator.js:186:19
    at Validator.validate (/home/vadim/Projects/Elysium/api/node_modules/fastest-validator/lib/validator.js:64:10)
    at Object.<anonymous> (/home/vadim/.WebStorm2019.3/config/scratches/scratch.es6:305:15)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
```

**Comment by icebob** [comment]
Sry, the example is not correct. I will fix it.

It's the correct syntax: https://repl.it/@icebob/custom-validator

**Comment by HighSoftWare96** [comment]
@icebob Please update the documentation
