### ISSUE TITLE
Can't extend built-in validation for array

### ISSUE THREAD

**Issue by mrspartak** [icebob/fastest-validator#136]
So the example is here https://repl.it/repls/TemporalUnfoldedProcessor
```javascript
const schema = {
  distribution: {
    type: 'array',
    min: 1,
    custom(val, errors) {
      //I don't get this message below
      console.log('distribution', val)
      return val
    },
    items: {
      type: 'number', convert: true,
      positive: true
    }
  },
};
```

The custom key is not working. Also, I don't use your library directly, I use moleculer framework and get this error when I put 'custom' key on arrays. On everything else works just fine.
```
Error [TypeError]: Cannot read property 'call' of undefined
at Array.eval (eval at compileRule (\node_modules\fastest-validator\lib\validator.js:
234:16), <anonymous>:136:36)
at Validator.eval (eval at compile (\node_modules\fastest-validator\lib\validator.js:
176:19), <anonymous>:10:14)
at \node_modules\fastest-validator\lib\validator.js:192:19
at validateContextParams (\moleculer\src\validator.js:48:17)
```

**Comment by icebob** [comment]
@erfanium do you have any idea?
It said:
```js
undefined:66
   const res = rule.schema.custom.call(this, parentObj.distribution, rule.schema, "distribution", parent, context);
```

**Comment by icebob** [comment]
Fix is released in 1.4.1

**Comment by mrspartak** [comment]
That was fast! Thanks a lot! Do I need to make an issue on a moleculer repo or release will come a bit later?

**Comment by icebob** [comment]
No problem.
No need a new release from moleculer. NPM can update in your project, just run an `npm update` in your project.

**Comment by mrspartak** [comment]
That worked fine.
I am stuck with one more thing. In the docs I see an error argument as second parameter at custom validation. But I get another structure with any type, not only arrays:
```javascript
const schema = {
  distribution: {
    type: 'array',
    min: 1,
    custom(...arguments) {
      console.log('distribution', arguments)
      return arguments[0]
    },
    items: {
      type: 'number', convert: true,
      positive: true
    }
  },
};
```

I get this args:
1. is value
2. is the object, that describes validation rules
```javascript
{
    type: 'array',
    min: 1,
    items: { type: 'number', convert: true, positive: true },
    custom: [Function: custom]
}
```
3. is a name of the key `distribution`
4. is null
5. is some global object
```javascript
{
    index: 19,
    rules: [
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object]
    ],
    fn: [
      [Function: anonymous], [Function: anonymous],
      [Function: anonymous], [Function: anonymous],
      [Function: anonymous], [Function: anonymous],
      [Function: anonymous], [Function: anonymous],
      [Function: anonymous], [Function: anonymous],
      [Function: anonymous], [Function: anonymous],
      [Function: anonymous], [Function: anonymous],
      [Function: anonymous], [Function: anonymous],
      [Function: anonymous], [Function: anonymous],
      [Function: anonymous]
    ],
    customs: {
      '$$root': [Object],
      //all my keys
    },
    data: {
      //input data object
    }
  }
```

So I don't see a way to trigger an error this way

**Comment by icebob** [comment]
@mrspartak please check it: https://github.com/icebob/fastest-validator/blob/master/CHANGELOG.md#new-custom-function-signature

**Comment by mrspartak** [comment]
Oh, I see. Now everything works fine!
