### ISSUE TITLE
TypeScript usage example.

### ISSUE THREAD

**Issue by R3VoLuT1OneR** [icebob/fastest-validator#170]
Hi, thank you for great library.

I am wondering how people use the library with TS.

If I do `import FastestValidator from "fastest-validator"` then in typescript FastestValidator defined as class.
But actually it is undefined after compile.

If I do `import * as FastestValidator from "fastest-validator" then I got next error when I try "new FastestValidator()"
```
This expression is not constructable.
  Type 'typeof import("fastest-validator")' has no construct signatures.
```
But aftest tsc compile "FastestValidator" is actually constructor function.

Also I can't use `FastestValidator` as a namespace, example: `const rule: FastestValidator.RuleAny = ...x;`.

So I do import next way, just to make validator work somehow.
```
import * as FastestValidator from 'fastest-validator';
import Validator, { ValidationSchema } from 'fastest-validator'; // tslint:disable-line
const ValidatorConstructor: any = FastestValidator;

const validator: Validator = new ValidatorConstructor(options);
```

What I am doing wrong? Can someone provide proper usage example?

**Comment by erfanium** [comment]
I have no problem with this code! 
```ts
import FV from 'fastest-validator'
const fv = new FV()
console.log(fv)
```

**Comment by R3VoLuT1OneR** [comment]
@erfanium I doing next:

```shell
npm install typescript fastest-validator
./node_modules/.bin/tsc --init
./node_modules/.bin/tsc index.ts

nodejs index.js
```

I got:
```
/tmp/fastest-validator/index.js:5
var fv = new fastest_validator_1["default"]();
         ^

TypeError: fastest_validator_1.default is not a constructor
    at Object.<anonymous> (/tmp/fastest-validator/index.js:5:10)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

@erfanium Can you please share your `tsconfig.json` please.

**Comment by erfanium** [comment]
```json
{
   "compileOnSave": false,
   "compilerOptions": {
      "experimentalDecorators": true,
      "allowJs": false,
      "module": "commonjs",
      "esModuleInterop": true,
      "target": "es2017",
      "moduleResolution": "node",
      "baseUrl": ".",
      "outDir": "./dist",
      "pretty": true,
      "lib": ["dom", "es2015", "es2016", "es2017"],
      "paths": {
         "*": ["*", "node_modules/*"]
      },
      "typeRoots": ["./node_modules/@types", "./typings"],
      "noImplicitAny": true,
      "noImplicitReturns": true,
      "noUnusedLocals": true,
      "resolveJsonModule": true
   },
   "include": ["."]
}
```

**Comment by erfanium** [comment]
@R3VoLuT1OneR What's happen if you run you code via `ts-node`?

**Comment by R3VoLuT1OneR** [comment]
@erfanium With `ts-node` it is working. It is working with `esModuleInterop: true`.

**Comment by erfanium** [comment]
@R3VoLuT1OneR So can I close this issue?

**Comment by R3VoLuT1OneR** [comment]
Yeah, I am closing it.

Another option if someone got it use: `"allowSyntheticDefaultImports": true`

**Comment by hemedani** [comment]
Deno does not support both of `allowSyntheticDefaultImports ` and `esModuleInterop `.
throwing this error :
```bash
Unsupported compiler options in "/Users/syd/work/lwob/packages/nsr/tsconfig.json".
  The following options were ignored:
    allowSyntheticDefaultImports, esModuleInterop
error: TS2351 [ERROR]: This expression is not constructable.
  Type '{}' has no construct signatures.
const v = new FastestValidator();
```

**Comment by erfanium** [comment]
@hemedani Would you like to create a PR for this?
