### ISSUE TITLE
BUG: "SyntaxError: Identifier 'res' has already been declared" when multiple custom rules are used

### ISSUE THREAD

**Issue by JMS-1** [icebob/fastest-validator#202]
Seems as if the code regenerator tries to reuse a const res.

```javascript
const Validator = require('fastest-validator')

const validator = new Validator()

const bad = {
    $$strict: true,
    mui: {
        properties: {
            de: {
                custom() {
                    return true
                },
                type: 'string',
            },
            en: {
                custom() {
                    return true
                },
                type: 'string',
            },
        },
        strict: true,
        type: 'object',
    },
}

validator.validate({}, bad)
```

seen in 1.8.0 and 1.9.0.

Full error stack running node &lt;code from above&gt;: 

```
undefined:42
                                const res = rule3.schema.custom.call(this, parentObj.en, rule3.schema, "mui.en", parent, context);
                                      ^

SyntaxError: Identifier 'res' has already been declared
    at new Function (<anonymous>)
    at Validator.compileRule (bad-fast/node_modules/fastest-validator/lib/validator.js:258:15)
    at Validator.module.exports (bad-fast/node_modules/fastest-validator/lib/rules/object.js:67:25)
    at Validator.compileRule (bad-fast/node_modules/fastest-validator/lib/validator.js:256:34)
    at Validator.compile (bad-fast/node_modules/fastest-validator/lib/validator.js:181:24)
    at Validator.validate (bad-fast/node_modules/fastest-validator/lib/validator.js:87:22)
    at Object.<anonymous> (bad-fast/index.js:27:11)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
```

Works fine when one of the custom rules is removed.

**Comment by JMS-1** [comment]
Quick fix if too complicated: use var instead of const (will make many javascript programmers really sad ;-) ).

**Comment by erfanium** [comment]
@JMS-1 Do you need a quick fix? I have a better idea but it may take a while

**Comment by JMS-1** [comment]
For now I have a solution for this very problem - not very elegant but it works. have a real fix some day would be nice.
