### ISSUE TITLE
BUG?: string pattern not working for this particular regex pattern

### ISSUE THREAD

**Issue by samseew** [icebob/fastest-validator#221]
Hello, I found this weird bug and I wanted to see what the problem was. Regex always worked fine when I used the 'pattern' attribute. But for some reason, when I use this particular regex for validating emails, it doesnt work and errors out the validator. I made sure the regex worked, it works in the online regex checkers and when I tested it with javascript it worked fine. Below I have an example that works fine and then the bug.

```
// works
const workingReg = /^[0-9]{10}$/

const noBug = validator.validate({ current_value: "test@test.com" }, { current_value: { type: "string", pattern: workingReg } });
console.log(noBug);

// doesnt work - even though it works when I test the regex with normal javascript
const reg = /^(([^<>()[]\.,;:\s@"]+(.[^<>()[]\.,;:\s@"]+)*)|(".+"))@(([[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}])|(([a-zA-Z-0-9]+.)+[a-zA-Z]{2,}))$/
console.log("testedRegex", reg.test("test@test.com"));

const bug = validator.validate({ current_value: "test@test.com" }, { current_value: { type: "string", pattern: reg } });
console.log(bug);
```

output:
```
[
  {
    type: 'stringPattern',
    message: "The 'current_value' field fails to match the required pattern.",
    field: 'current_value',
    expected: '/^[0-9]{10}$/',
    actual: 'test@test.com'
  }
]

testedRegex true

undefined:20
errors.push({ type: "stringPattern", message: "The '{field}' field fails to match the required pattern.", field: field, expected: "/^(([^<>()[]\.,;:\s@"]+(.[^<>()[]\.,;:\s@"]+)*)|(".+"))@(([[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}])|(([a-zA-Z-0-9]+.)+[a-zA-Z]{2,}))$/", actual: origValue });
^

SyntaxError: Unexpected token ']'
at new Function ()
at Validator.compileRule (/Users/sashtar/development/hdc/hdc-datastore/node_modules/fastest-validator/lib/validator.js:258:15)
at Validator.module.exports (/Users/sashtar/development/hdc/hdc-datastore/node_modules/fastest-validator/lib/rules/object.js:67:25)
at Validator.compileRule (/Users/sashtar/development/hdc/hdc-datastore/node_modules/fastest-validator/lib/validator.js:256:34)
at Validator.compile (/Users/sashtar/development/hdc/hdc-datastore/node_modules/fastest-validator/lib/validator.js:181:24)
at Validator.validate (/Users/sashtar/development/hdc/hdc-datastore/node_modules/fastest-validator/lib/validator.js:87:22)
at Object. (/Users/sashtar/development/hdc/hdc-datastore/src/rules-engine/validation-service.js:52:23)
at Module._compile (internal/modules/cjs/loader.js:1076:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
at Module.load (internal/modules/cjs/loader.js:941:32)```

**Comment by intech** [comment]
Problem on this line:
https://github.com/icebob/fastest-validator/blob/master/lib/rules/string.js#L140-L143
the replace method breaks the string

**Comment by samseew** [comment]
@intech right, and I am assuming this is unexpected behavior. will there be a fix?

**Comment by intech** [comment]
@samseew fixed, wait for next release

**Comment by samseew** [comment]
@intech Thank you! When does the next release come out?

**Comment by erfanium** [comment]
@samseew You can install fastest-validator directly from Github until the release

**Comment by samseew** [comment]
@erfanium @intech  got it, thanks guys
