### ISSUE TITLE
Async validations from README doesn`t work

### ISSUE THREAD

**Issue by FenixDeveloper** [icebob/fastest-validator#234]
Node.JS 16.1.0
npm 7.12.0
fastest-validator 1.10.1

Example code:
```
const Validator = require("fastest-validator");

(async function main() {

	const v = new Validator({
	    useNewCustomCheckerFunction: true, // using new version
	    messages: {
	        // Register our new error message text
	        unique: "The username is already exist"
	    }
	});

	const exist = ['user1'];

	const schema = {
	    $$async: true,
	    name: { type: "string" },
	    username: {
	        type: "string",
	        min: 2,
	        custom: async (v, errors) => {
	            if (exist.indexOf(v) !== -1)
	            	errors.push({ type: "unique", actual: v });

	            return v;
	        }
	    }
	    // ...
	};

	const check = v.compile(schema);

	const res = await check({
		name: 'test',
		username: 'user1'
	});

	console.log("Result:", res);

})().then(() => {
	console.log(`\n\nComplete.`);
});
```

Console output:
```
$ node constraints-test.js
D:\WORKSPACE\GIT\NEBULA24\NB24-CRM-V3\api\node_modules\fastest-validator\lib\validator.js:314
                        throw new Error("Invalid '" + schema.type + "' type in validator schema.");
                              ^

Error: Invalid 'undefined' type in validator schema.
    at Validator.getRuleFromSchema (D:\WORKSPACE\GIT\NEBULA24\NB24-CRM-V3\api\node_modules\?[4mfastest-validator?[24m\lib\validator.js:314:10)
    at Validator.module.exports (D:\WORKSPACE\GIT\NEBULA24\NB24-CRM-V3\api\node_modules\?[4mfastest-validator?[24m\lib\rules\object.js:63:22)
    at Validator.compileRule (D:\WORKSPACE\GIT\NEBULA24\NB24-CRM-V3\api\node_modules\?[4mfastest-validator?[24m\lib\validator.js:256:34)
    at Validator.compile (D:\WORKSPACE\GIT\NEBULA24\NB24-CRM-V3\api\node_modules\?[4mfastest-validator?[24m\lib\validator.js:181:24)
    at main (D:\WORKSPACE\GIT\NEBULA24\NB24-CRM-V3\api\constraints-test.js:31:18)
    at Object.<anonymous> (D:\WORKSPACE\GIT\NEBULA24\NB24-CRM-V3\api\constraints-test.js:40:3)
?[90m    at Module._compile (node:internal/modules/cjs/loader:1109:14)?[39m
?[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)?[39m
?[90m    at Module.load (node:internal/modules/cjs/loader:989:32)?[39m
?[90m    at Function.Module._load (node:internal/modules/cjs/loader:829:14)?[39m
```

Have any workaround for correct async validation or may be i did something wrong?

**Comment by icebob** [comment]
Async is not yet released. Until then, install the master branch with `npm i icebob/fastest-validator`.

**Comment by erfanium** [comment]
@icebob Better to release a bata version
