### ISSUE TITLE
v0.6.11 broke some specific schemas

### ISSUE THREAD

**Issue by p0vidl0** [icebob/fastest-validator#35]
I use UUID literals nested keys in validation schema its work on 0.6.10 and was broken in 0.6.11.
Simple example code:
```js
const schema = {
  minPrice: {
    type: 'object',
    props: {
      value: { type: 'number', positive: true, integer: true },
      enabled: 'boolean',
      regions: {
        type: 'object',
        optional: true,
        props: { '12345678-ef85-4c62-b8f3-e00fbbc155d4': { type: 'number', positive: true, integer: true, optional: true } },
      },
    },
  },
};

/**
 * Next line throws
 * SyntaxError: Invalid or unexpected token
 * at new Function (<anonymous>)
 * at Validator.compileSchemaObject (node_modules\fastest-validator\lib\validator.js:114:33)
 * at Validator.compileSchemaRule (node_modules\fastest-validator\lib\validator.js:154:24)
 * at Validator.compileSchemaType (ec-order\node_modules\fastest-validator\dist\index.js:472:15)
 *
 * Generated code looks like
 * propertyPath = (path !== undefined ? path + ".12345678-ef85-4c62-b8f3-e00fbbc155d4" : "12345678-ef85-4c62-b8f3-e00fbbc155d4");
 * res = this.checkSchemaRule(value.12345678-ef85-4c62-b8f3-e00fbbc155d4, compiledObject[0].compiledType, propertyPath, value);
 * if (res !== true) {             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 *  this.handleResult(errors, propertyPath, res);
 * }
 */
const result = v.validate(data, schema);
```

At the moment, I don't have enough time to make a pull request.

**Comment by andersnm** [comment]
Ahh, this makes me feel bad, I'm sorry! I can make a PR within a few days unless somebody beats me to it.

I believe the main performance improvement in .11 comes from accessing properties directly by name in the generated code. But of course, JavaScript objects are also string-keyed dictionaries, so it should generate different code if the property cannot be accessed directly by name - which includes reserved keywords! Guess a regex + blacklist in the compiler comes a long way to solve it while remaining performant.
