### ISSUE TITLE
Incorrect typescript type definition 

### ISSUE THREAD

**Issue by sigoden** [icebob/fastest-validator#71]
index.ts
```
import  Validator from "fastest-validator";

let v = new Validator();
```

ts-node index.ts
```
let v = new Validator();
        ^
TypeError: fastest_validator_1.default is not a constructor
    at Object.<anonymous> (/tmp/test/index.ts:3:9)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module.m._compile (/home/sigoden/.nvm/versions/node/v10.15.1/lib/node_modules/ts-node/src/index.ts:439:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/sigoden/.nvm/versions/node/v10.15.1/lib/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at Object.<anonymous> (/home/sigoden/.nvm/versions/node/v10.15.1/lib/node_modules/ts-node/src/bin.ts:154:12)
```

**Comment by icebob** [comment]
`import * as Validator from "fastest-validator";`

**Comment by wi-ski** [comment]
This doesnt work for me. Does this work for anyone?

**Comment by wi-ski** [comment]
```sh
This expression is not constructable.
  Type 'typeof import("fastest-validator")' has no construct signatures.

16 const validator = new Validator({
                         ~~~~~~~~~

    at createTSError (/home/wiski/projects/namedomain/node_modules/ts-node/src/index.ts:421:12)
    at reportTSError (/home/wiski/projects/namedomain/node_modules/ts-node/src/index.ts:425:19)
```

**Comment by wi-ski** [comment]
```sh
This expression is not constructable.
  Type 'typeof import("fastest-validator")' has no construct signatures.

16 const validator = new Validator({
                         ~~~~~~~~~

    at createTSError (/home/wiski/projects/namedomain/node_modules/ts-node/src/index.ts:421:12)
    at reportTSError (/home/wiski/projects/namedomain/node_modules/ts-node/src/index.ts:425:19)

```

**Comment by icebob** [comment]
@akazakou do you have any clue?

**Comment by akazakou** [comment]
@wi-ski @icebob Looks like a bug in ts-node. If we are not using [tslib](https://www.npmjs.com/package/tslib) to handle require functionality, I've also had the same issue. But based on my gist it works fine https://gist.github.com/akazakou/20d4368d087a9d874eecd65f9e8f70d8

**Comment by akazakou** [comment]
After a deep investigation, I found that it not working without enabled `esModuleInterop` option for ts-node

```shell
TS_NODE_COMPILER_OPTIONS='{"esModuleInterop": true}' ts-node index.ts
```
